job('rasputnik-game-of-life') {
  description('generated by job-seeder')
    scm {
        github('rasputnik/game-of-life')
    }
    triggers {
        scm('H/5 * * * *')
    }
    steps {
        maven('-e clean test')
    }
}
